AcmeTestBundle_homepage:
    pattern:  /test
    defaults: { _controller: AcmeTestBundle:Default:index };
AcmeTestBundle_create:
    pattern:  /create
    defaults: { _controller: AcmeTestBundle:Default:create };
AcmeTestBundle_showAll:
    pattern:  /showAll
    defaults: { _controller: AcmeTestBundle:Default:showAll };
AcmeTestBundle_query:
    pattern:  /query
    defaults: { _controller: AcmeTestBundle:Default:query };