Acme\MsgbBundle\Entity\msgb_admin:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    account:
      type: string
      length: '255'
    password:
      type: string
      length: '255'
    nickname:
      type: string
      length: '255'
  lifecycleCallbacks: {  }
