AcmeMsgbBundle:
    resource: "@AcmeMsgbBundle/Resources/config/routing.yml"
    prefix:   /msgb/

AcmeMsgBundle:
    resource: "@AcmeMsgBundle/Resources/config/routing.yml"
    prefix:   /msg/

AcmeTestBundle:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
