parameters:
#    acme_msgb.example.class: Acme\MsgbBundle\Example

services:
#    acme_msgb.example:
#        class: %acme_msgb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
