Acme\MsgbBundle\Entity\msgb:
    properties:
        account:
            - Regex:
                pattern: "/^[A-Za-z0-9]{4,12}$/"
                match:   "false"
                message: "Account : Please insert 4~12 alphabets or numbers"
        nickname:
            - Regex:
                pattern: "/^.{2,12}$/"
                match:   "false"
                message: "Nickname : Please insert 2~12 characters"
        mobile:
            - Regex:
                pattern: "/^[0-9]{9,12}$/"
                match:   "false"
                message: "Mobile : Please insert 9~12 numbers"
Acme\MsgbBundle\Entity\msgb_admin:
    properties:
        account:
            - Regex:
                pattern: "/^[A-Za-z0-9]{4,12}$/"
                match:   "false"
                message: "Account : Please insert 4~12 alphabets or numbers"
        password:
            - Regex:
                pattern: "/^[a-zA-Z0-9]{4,12}$/"
                match:   "false"
                message: "Password : Please insert 4~12 alphabets or numbers"
        nickname:
            - Regex:
                pattern: "/^.{2,12}$/"
                match:   "false"
                message: "Nickname : Please insert 2~12 characters"
