<?php

namespace Acme\MsgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * msgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class msgRepository extends EntityRepository
{
}