parameters:
#    acme_msg.example.class: Acme\MsgBundle\Example

services:
#    acme_msg.example:
#        class: %acme_msg.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
