<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AcmeMsgbBundleEntitymsgbProxy extends \Acme\MsgbBundle\Entity\msgb implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setAccount($account)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setNickname($nickname)
    {
        $this->__load();
        return parent::setNickname($nickname);
    }

    public function getNickname()
    {
        $this->__load();
        return parent::getNickname();
    }

    public function setMobile($mobile)
    {
        $this->__load();
        return parent::setMobile($mobile);
    }

    public function getMobile()
    {
        $this->__load();
        return parent::getMobile();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setContant($contant)
    {
        $this->__load();
        return parent::setContant($contant);
    }

    public function getContant()
    {
        $this->__load();
        return parent::getContant();
    }

    public function setTime($time)
    {
        $this->__load();
        return parent::setTime($time);
    }

    public function getTime()
    {
        $this->__load();
        return parent::getTime();
    }

    public function setIp($ip)
    {
        $this->__load();
        return parent::setIp($ip);
    }

    public function getIp()
    {
        $this->__load();
        return parent::getIp();
    }

    public function setReplyer($replyer)
    {
        $this->__load();
        return parent::setReplyer($replyer);
    }

    public function getReplyer()
    {
        $this->__load();
        return parent::getReplyer();
    }

    public function setReply_contant($reply_contant)
    {
        $this->__load();
        return parent::setReply_contant($reply_contant);
    }

    public function getReply_contant()
    {
        $this->__load();
        return parent::getReply_contant();
    }

    public function setReply_time($reply_time)
    {
        $this->__load();
        return parent::setReply_time($reply_time);
    }

    public function getReply_time()
    {
        $this->__load();
        return parent::getReply_time();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'account', 'nickname', 'mobile', 'title', 'contant', 'time', 'ip', 'replyer', 'reply_contant', 'reply_time');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}