<?php

namespace Acme\MsgbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * msgbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class msgbRepository extends EntityRepository
{
}