<?php

namespace Acme\MsgbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * msgb_logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class msgb_logRepository extends EntityRepository
{
}